In [1]:
import numpy as np

In [2]:
arr = np.array([1,5,3,4,8,2,1,5])

In [4]:
m = max(arr)
ind = -1
for i in range(arr.shape[0]):
    if arr[i] == m:
        ind = i
        break

In [5]:
ind

4

In [6]:
np.argmax(arr)

4

In [7]:
np.argmin(arr)

0

In [8]:
arr = np.arange(16).reshape(-1,4)[::-1]
arr

array([[12, 13, 14, 15],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [9]:
arr.reshape(-1)

array([12, 13, 14, 15,  8,  9, 10, 11,  4,  5,  6,  7,  0,  1,  2,  3])

In [10]:
np.argmin(arr)

12

In [11]:
np.argmin(arr, axis=0)

array([3, 3, 3, 3], dtype=int64)

In [12]:
np.argmin(arr, axis=1)

array([0, 0, 0, 0], dtype=int64)

In [13]:
np.amin(arr)

0

In [14]:
np.amax(arr)

15

In [16]:
np.amin(arr, axis=0)

array([0, 1, 2, 3])

In [17]:
np.amin(arr, axis=1)

array([12,  8,  4,  0])

In [18]:
nan_inf_arr = np.array([1, 2, np.inf, 4, 5, np.nan, 7, 8, np.nan])
nan_inf_arr

array([ 1.,  2., inf,  4.,  5., nan,  7.,  8., nan])

In [19]:
np.isinf(nan_inf_arr)

array([False, False,  True, False, False, False, False, False, False])

In [20]:
np.isnan(nan_inf_arr)

array([False, False, False, False, False,  True, False, False,  True])

In [21]:
np.nanmax(nan_inf_arr)

inf

In [22]:
np.nanmin(nan_inf_arr)

1.0

In [23]:
np.ptp(arr)

15

In [24]:
np.ptp(arr, axis=0)

array([12, 12, 12, 12])

In [35]:
perc = 60
array = np.random.randn(100_000)

In [36]:
array = np.sort(array)
ind = array.shape[0]*perc/100
ind = int(ind)
ind

60000

In [37]:
array[ind]

0.25372907668203837

In [38]:
from matplotlib import pyplot as plt

In [39]:
h = plt.hist(array)

In [40]:
h = plt.hist(np.sort(array)[:ind], bins=5)

In [31]:
np.quantile(array, 0.6)

0.25275404646662814

In [32]:
np.percentile(array, 60)

0.25275404646662814

In [41]:
np.median(array)

0.0038823566498624425

In [42]:
np.quantile(array, 0.5)

0.0038823566498624425

In [43]:
np.mean(array)

0.0023386211846841798

In [44]:
np.average(array)

0.0023386211846841798

In [45]:
arr = np.arange(1,10)
weights = 1/arr

In [46]:
np.average(arr, weights=weights)

3.181371861411138

In [47]:
np.std(array)

0.9997347619858932

In [48]:
a = np.arange(10)
b = a[::-1]

np.corrcoef(a,b)

array([[ 1., -1.],
       [-1.,  1.]])

In [49]:
noisy_b = b + np.random.randn(b.shape[0]) * b.std()/10

In [50]:
noisy_b

array([8.91312082, 7.86349044, 7.10664721, 5.70607576, 4.83182048,
       3.57299191, 3.3185182 , 2.12833827, 0.83136429, 0.10521729])

In [52]:
np.corrcoef(a, noisy_b)

array([[ 1.        , -0.99734858],
       [-0.99734858,  1.        ]])